---
  - name: check flag
    stat: path=/tmp/ansible-ongoing
    register: ongoing

  - name: set flag for vagrant to run ansible provisioner once
    file: path=/tmp/ansible-ongoing state=touch
    when: ongoing.stat.exists == false

  - include: mount.yml
    when: ongoing.stat.exists == false

  - name: remove flag
    file: path=/tmp/ansible-ongoing state=absent
    