---
# install & configure ambari-server
  - name: install different packages Mysql related + curl
    yum: name={{ item }} state=present
    with_items:
      - mysql-connector-java
      - mariadb
      - MySQL-python
      - python-httplib2
      - curl


