---
# install & configure ambari-server 
  - name: install different packages Mysql related + curl
    yum: name={{ item }} state=present
    with_items:
      - mysql-connector-java
      - mysql
      - MySQL-python
      - python-httplib2
      - curl

  - name: import ambari-server schema
    mysql_db: name={{ hostvars[groups['db_server'][0]]['ambari_db'] }} state=import login_host={{ hostvars[groups['db_server'][0]]['ansible_fqdn'] }} login_user={{ hostvars[groups['db_server'][0]]['ambari_user'] }} login_password={{ hostvars[groups['db_server'][0]]['ambari_password'] }}  target=/var/lib/ambari-server/resources/Ambari-DDL-MySQL-CREATE.sql

  - name: configure ambari to use mysql
    shell: /usr/sbin/ambari-server setup --jdbc-db=mysql --jdbc-driver=/usr/share/java/mysql-connector-java.jar

  - name: configure ambari server with mysql
		shell: /usr/sbin/ambari-server setup -s --database=mysql --databasehost={{ hostvars[groups['db_server'][0]]['ansible_fqdn'] }} --databaseport=3306 --databasename={{ hostvars[groups['db_server'][0]]['ambari_db'] }}  --databaseusername={{ hostvars[groups['db_server'][0]]['ambari_user'] }}  --databasepassword={{ hostvars[groups['db_server'][0]]['ambari_password'] }}  -j {{ java_home }}
