---
  - name: install libselinux-python
    yum: name=libselinux-python state=present

# Disable hugepage in grub
  - name: disable Hugepage in grub default
    register: grub_config
    lineinfile: dest=/etc/default/grub
      backup=True
      backrefs=True
      state=present
      regexp='GRUB_CMDLINE_LINUX="(?!transparent_hugepage=never)([^"]*)"'
      line='GRUB_CMDLINE_LINUX="transparent_hugepage=never \1"'

  - name: Write grub configuration file
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    when: grub_config.changed

  - name: Write grub to MBR
    command: grub2-install /dev/xvda
    when: grub_config.changed

# Disable selinux
  - name: disable selinux
    shell: setenforce 0
    ignore_errors: true
  - name: switch off selinux permanently
    lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled
      backup=True
      backrefs=True
    register: ambari_installed

# Install and configure Java
  - name: install java
    yum: name={{ item }} state=present
    with_items:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel

  - name: configure java
    template: src=java.sh.j2 dest=/etc/profile.d/java.sh

# Install & configure ntp
  - name: install ntp server
    yum: name=ntp state=present
  - name: switch on ntpd
    service: name=ntpd state=started enabled=on

# Disable iptables
  - name: Check if firewall is install
    command: rpm -q firewalld
    register: rpm_check
    ignore_errors: true

  - name: switch off firewall
    service: name=firewalld state=stopped enabled=off
    when: rpm_check.rc == 0

# Restart server and check if it's up
  - name: restart machine
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true
    when: ambari_installed|changed
    
  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }}
      state=started
      port=22
      delay=15
      timeout=600
    become: false
    when: ambari_installed|changed
