---
- hosts: all
  become_user: root
  become: yes
  roles:
    - mount
    - prep
    - users

- hosts: db_server
  become_user: root
  become: yes
  roles:
    - db-server

- hosts: ambari_server
  become_user: root
  become: yes
  roles:
    - ambari-server
